### ISSUE TITLE
[BUG] Ed25519 Will Not Work With Current QUIC Library

### ISSUE THREAD

**Issue by bonedaddy** [uhthomas/pastry#2]
Relevant issue: https://github.com/lucas-clemente/quic-go/issues/2006

Running the `cmd/pastry` package and am unable to dial between peers due to the usage of ed25519, and the tls library used by quic-go not fully supporting it.

Error:

```
2019/10/13 20:44:24 failed to dial and accept:  CRYPTO_ERROR: tls: internal error
```

**Comment by uhthomas** [comment]
I'm not sure it's ed25519's fault. It seems more likely that since a `nil` TLS config is passed to both `Accept` and `Listen`, that connections are rejected. Using [quic-go's example TLS config generator](https://github.com/lucas-clemente/quic-go/blob/master/example/echo/echo.go#L92) seems to work fine.

There should probably be a distinction between transport and application layer crypto. One of my initial ideas was using mutual TLS, but it might be better to make the protocol transport-agnostic.

**Comment by bonedaddy** [comment]
Darn  perhaps that is it, I tried making changes like the following to work but no dice!

```Golang
 quic.ListenAddr(address, &tls.Config{InsecureSkipVerify: true}, nil)
```

> There should probably be a distinction between transport and application layer crypto. One of my initial ideas was using mutual TLS, but it might be better to make the protocol transport-agnostic.

Definitely! That's also something libp2p can help with :D 

update:

Yes using the quic-go example tls generator worked. Woot!

**Comment by uhthomas** [comment]
Awesome! Glad it works for you! :)
